
CREATE TABLE USER (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL,
  password varchar(45) NOT NULL,
  email varchar(45) NOT NULL,
  PRIMARY KEY (id)
) ;

CREATE TABLE PRODUCT(
ID INTEGER NOT NULL AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(30),
PRODUCT_PRICE DECIMAL(6,4),
PRIMARY KEY (ID)
);

CREATE TABLE STOCK(
ID INTEGER NOT NULL AUTO_INCREMENT,
PRODUCT_ID INTEGER,
QTY_IN_HAND INTEGER,
PRIMARY KEY (ID),
CONSTRAINT FK_PRODUCT_STOCK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE COMPANY(
ID INTEGER NOT NULL AUTO_INCREMENT,
COMPANY_NAME VARCHAR(30),
PRIMARY KEY (ID)
);

CREATE TABLE FARM(
ID INTEGER NOT NULL AUTO_INCREMENT,
FARM_NAME VARCHAR(30),
COMPANY_ID INTEGER,
PRIMARY KEY (ID),
CONSTRAINT FK_COMPANY_FARM FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
);

CREATE TABLE TAG(
ID INTEGER NOT NULL AUTO_INCREMENT,
TAG_NAME VARCHAR(30),
PRIMARY KEY (ID)
);

CREATE TABLE PURCHASE(
ID INTEGER NOT NULL AUTO_INCREMENT,
PURCHASE_DATE DATE,
PRIMARY KEY (ID)
);

CREATE TABLE PURCHASE_TYPE(
ID INTEGER NOT NULL AUTO_INCREMENT,
PURCHASE_TYPE VARCHAR(20),
PRIMARY KEY (ID)
);

CREATE TABLE ANIMAL(
ID INTEGER NOT NULL AUTO_INCREMENT,
TAG_ID INTEGER,
FARM_ID INTEGER,
BIRTH_DATE DATE,
BIRTH_WEIGHT DECIMAL,
PURCHASE_ID INTEGER,
ANIMAL_NAME VARCHAR(30),
ANIMAL_INITIAL_PRICE DECIMAL,
PRIMARY KEY (ID),
CONSTRAINT FK_TAG_ANIMAL FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
CONSTRAINT FK_PURCHASE_ANIMAL FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE(ID),
CONSTRAINT FK_FARM_ANIMAL FOREIGN KEY (FARM_ID) REFERENCES FARM(ID)
);

CREATE TABLE PURCHASE_DETAIL(
ID INTEGER NOT NULL AUTO_INCREMENT,
PURCHASE_ID INTEGER,
PRODUCT_ID INTEGER,
ANIMAL_ID INTEGER,
TYPE_ID INTEGER,
QUANTITY INTEGER,
PRICE DECIMAL,
PRIMARY KEY (ID),
CONSTRAINT FK_PURCHASE_PURCHASE_DETAIL FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE(ID),
CONSTRAINT FK_PRODUCT_PURCHASE_DETAIL FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
CONSTRAINT FK_ANIMAL_PURCHASE_DETAIL FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID),
CONSTRAINT FK_PURCHASE_TYPE_PURCHASE_DETAIL FOREIGN KEY (TYPE_ID) REFERENCES PURCHASE_TYPE(ID)
);

CREATE TABLE FEED_USED(
ID INTEGER NOT NULL AUTO_INCREMENT,
ANIMAL_ID INTEGER,
QUANTITY INTEGER,
PRIMARY KEY (ID),
CONSTRAINT FK_ANIMAL_FEED_USED FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID)
);

CREATE TABLE ANIMAL_PRICE(
ID INTEGER NOT NULL AUTO_INCREMENT,
ANIMAL_ID INTEGER,
VERSION INTEGER,
PRICE DOUBLE,
PRIMARY KEY (ID),
CONSTRAINT FK_ANIMAL_ANIMAL_PRICES FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID)
);